In [25]:
import logging, os

import pandas as pd
import numpy as np

logging.basicConfig(format = '%(asctime)-25s %(message)s', level = logging.INFO)

# Clean data from https://stockanalysis.com/stocks/

* Clean up data and save to CSV.
* Uncomment the last line to write CSV file. 
* Tickers without market cap are printed out (Mkt Cap set to 0)

In [3]:
stocks = '../data/sac_tickers_raw.csv'
stocks = open(stocks, 'r').readlines()
columns = [s.strip() for s in stocks[0].split('\t')]

parsed_data = []
for start in range(1,len(stocks)-2, 2):
    stock = stocks[start:start+2]
    parsed = stock[0].split('\t')[:-1]
    parsed[0] = parsed[0].replace('.', '-')
    mkt_cap = stock[1].strip()
    try:
        mkt_cap = round(float(mkt_cap[:-1].replace(',',''))*(1000 if mkt_cap[-1]=='B' else 1))
    except ValueError:
        print(parsed, mkt_cap)
        mkt_cap = 0
    parsed.append(mkt_cap)
    parsed_data.append(tuple(parsed))

df = pd.DataFrame(parsed_data, columns=columns)
df = df.set_index('Symbol')
#df.to_csv('../data/sac_tickers.csv')

['EIC', 'Eagle Point Income Company', 'n/a'] -
['OZ', 'Belpointe PREP, LLC', 'Real Estate-Development'] -
['SGML', 'Sigma Lithium', 'Other Industrial Metals & Mining'] -
['TCN', 'Tricon Residential', 'Real Estate Services'] -

### Find tickers in StockAnalysisCom NOT in AV

In [4]:
sac = pd.read_csv('../data/sac_tickers.csv')
av = pd.read_csv('../data/av_listed_tickers.csv')

mask = [not any(av['Symbol'].str.contains(s)) for s in sac['Symbol']]
sac[mask]

,Symbol,Company Name,Industry,Market Cap
125,ADXS,Advaxis,Biotechnology,16
146,AESE,Allied Esports Entertainment,"Hotels, Restaurants & Leisure",70
2645,HHS,Harte Hanks,Media,49
2886,IMH,Impac Mortgage Holdings,Thrifts & Mortgage Finance,16
5861,VGFC,The Very Good Food Company,Packaged Foods,66

### GroupBy Industry (also identify how many companies have n/a for Industry)

In [11]:
industries = sac.groupby('Industry', as_index=False, dropna=False).count()
print(industries.to_string())

sac[sac['Industry'].isnull()]

                                     Industry  Symbol  Company Name  Market Cap
0                        Advertising Agencies      14            14          14
1                         Aerospace & Defense      63            63          63
2                         Agricultural Inputs       2             2           2
3                     Air Freight & Logistics      13            13          13
4                                    Airlines      20            20          20
5                     Airports & Air Services       4             4           4
6                       Apparel Manufacturing       3             3           3
7                              Apparel Retail       7             7           7
8                            Asset Management      21            21          21
9                    Auto & Truck Dealerships       4             4           4
10                            Auto Components      35            35          35
11                         Auto Manufacturers      13            13          13
12                                 Auto Parts       6             6           6
13                                Automobiles      19            19          19
14                                      Banks     316           316         316
15                          Banks-Diversified       1             1           1
16                             Banks-Regional      19            19          19
17                                  Beverages      26            26          26
18                          Beverages-Brewers       1             1           1
19                    Beverages-Non-Alcoholic       5             5           5
20          Beverages-Wineries & Distilleries       4             4           4
21                              Biotechnology     686           686         686
22                         Blank Check / SPAC     696           696         696
23                               Broadcasting       4             4           4
24                          Building Products      36            36          36
25              Building Products & Equipment       4             4           4
26                            Capital Markets     153           153         153
27                                  Chemicals      84            84          84
28                                Coking Coal       1             1           1
29             Commercial Services & Supplies      64            64          64
30                    Communication Equipment       6             6           6
31                   Communications Equipment      60            60          60
32                          Computer Hardware       9             9           9
33                 Construction & Engineering      32            32          32
34                     Construction Materials      14            14          14
35                        Consulting Services       2             2           2
36                       Consumer Electronics       2             2           2
37                           Consumer Finance      41            41          41
38                     Containers & Packaging      19            19          19
39                            Credit Services       9             9           9
40   Data Processing, Hosting, and Related...       1             1           1
41                     Diagnostics & Research      15            15          15
42                            Discount Stores       1             1           1
43                               Distributors       8             8           8
44              Diversified Consumer Services      47            47          47
45             Diversified Financial Services      18            18          18
46     Diversified Telecommunication Services      24            24          24
47                 Drug Manufacturers-General       2             2           2
48     Drug Manufacturers-Specialty & Generic      20            20          20
49              Education & Training Services      12            12          12
50                         Electric Utilities      34            34          34
51                       Electrical Equipment      46            46          46
52               Electrical Equipment & Parts      10            10          10
53                      Electronic Components       8             8           8
54   Electronic Equipment, Instruments & C...     100           100         100
55             Electronic Gaming & Multimedia       8             8           8
56        Electronics & Computer Distribution       1             1           1
57                Energy Equipment & Services      60            60          60
58                 Engineering & Construction       3             3           3
59                              Entertainment      53            53          53
60   Equity Real Estate Investment Trusts ...     167           167         167
61        Farm & Heavy Construction Machinery       5             5           5
62                              Farm Products       5             5           5
63                   Food & Staples Retailing      27            27          27
64                              Food Products      67            67          67
65         Furnishings, Fixtures & Appliances       6             6           6
66                                   Gambling      11            11          11
67                              Gas Utilities      14            14          14
68                                       Gold       5             5           5
69                             Grocery Stores       5             5           5
70           Health Care Equipment & Supplies     167           167         167
71           Health Care Providers & Services      79            79          79
72                     Health Care Technology      26            26          26
73                Health Information Services      24            24          24
74                                 Healthcare       1             1           1
75                           Healthcare Plans       5             5           5
76                    Home Improvement Retail       2             2           2
77              Hotels, Restaurants & Leisure      98            98          98
78              Household & Personal Products       4             4           4
79                         Household Durables      57            57          57
80                         Household Products      12            12          12
81                                IT Services     106           106         106
82   Independent Power and Renewable Elect...      20            20          20
83                   Industrial Conglomerates       7             7           7
84                    Industrial Distribution       2             2           2
85            Information Technology Services      17            17          17
86                                  Insurance     101           101         101
87                          Insurance Brokers       7             7           7
88                      Insurance-Diversified       2             2           2
89                             Insurance-Life       1             1           1
90              Insurance-Property & Casualty       3             3           3
91                      Insurance-Reinsurance       1             1           1
92                        Insurance-Specialty       3             3           3
93             Integrated Freight & Logistics       1             1           1
94               Interactive Media & Services      50            50          50
95         Internet & Direct Marketing Retail      59            59          59
96             Internet Content & Information      16            16          16
97                            Internet Retail      18            18          18
98               Internet Software & Services       2             2           2
99   Investment Banking and Securities Dea...       1             1           1
100                                   Leisure       5             5           5
101                          Leisure Products      26            26          26
102     Lessors of Other Real Estate Property       1             1           1
103            Life Sciences Tools & Services      36            36          36
104                                   Lodging       2             2           2
105                              Luxury Goods       2             2           2
106                                 Machinery     113           113         113
107                                    Marine      25            25          25
108                           Marine Shipping       2             2           2
109                                     Media      71            71          71
110                   Medical Care Facilities      19            19          19
111                           Medical Devices      40            40          40
112            Medical Instruments & Supplies      13            13          13
113                         Metal Fabrication       1             1           1
114                           Metals & Mining     118           118         118
115                          Mortgage Finance       4             4           4
116  Mortgage Real Estate Investment Trust...      34            34          34
117                           Multi-Utilities      18            18          18
118                          Multiline Retail       9             9           9
119                        Oil & Gas Drilling       2             2           2
120                             Oil & Gas E&P       8             8           8
121            Oil & Gas Equipment & Services       5             5           5
122                       Oil & Gas Midstream       2             2           2
123               Oil, Gas & Consumable Fuels     207           207         207
124          Other Industrial Metals & Mining      10            10          10
125            Other Precious Metals & Mining       4             4           4
126                            Packaged Foods      16            16          16
127                    Packaging & Containers       4             4           4
128                   Paper & Forest Products      12            12          12
129                    Paper & Paper Products       1             1           1
130                         Personal Products      28            28          28
131                         Personal Services       6             6           6
132  Pharmaceutical Preparation Manufactur...       1             1           1
133               Pharmaceutical Preparations       1             1           1
134                  Pharmaceutical Retailers       5             5           5
135                           Pharmaceuticals     147           147         147
136  Photographic and Photocopying Equipme...       1             1           1
137            Pollution & Treatment Controls       3             3           3
138                     Professional Services      54            54          54
139                                Publishing       3             3           3
140                          REIT-Diversified       5             5           5
141                             REIT-Mortgage       7             7           7
142                               REIT-Office       2             2           2
143                          REIT-Residential       1             1           1
144                               REIT-Retail       2             2           2
145                            REIT-Specialty       1             1           1
146      Real Estate Management & Development      45            45          45
147                      Real Estate Services       7             7           7
148                   Real Estate-Development       4             4           4
149                   Real Estate-Diversified       1             1           1
150                     Recreational Vehicles       4             4           4
151                 Rental & Leasing Services       3             3           3
152                  Residential Construction       1             1           1
153                               Restaurants       8             8           8
154                               Road & Rail      30            30          30
155        Scientific & Technical Instruments       6             6           6
156        Securities and Commodity Exchanges       1             1           1
157            Security & Protection Services       4             4           4
158       Semiconductor Equipment & Materials       1             1           1
159                            Semiconductors       7             7           7
160  Semiconductors & Semiconductor Equipment      97            97          97
161                           Shell Companies      27            27          27
162                                  Software     195           195         195
163                      Software-Application      91            91          91
164                   Software-Infrastructure      52            52          52
165                                     Solar       4             4           4
166               Specialty Business Services       5             5           5
167                       Specialty Chemicals       5             5           5
168            Specialty Industrial Machinery       7             7           7
169                          Specialty Retail     102           102         102
170            Staffing & Employment Services       5             5           5
171                                     Steel       2             2           2
172  Technology Hardware, Storage & Periph...      32            32          32
173                          Telecom Services      11            11          11
174          Textiles, Apparel & Luxury Goods      41            41          41
175                Thrifts & Mortgage Finance      81            81          81
176                                   Tobacco       9             9           9
177                       Tools & Accessories       1             1           1
178          Trading Companies & Distributors      38            38          38
179             Transportation Infrastructure       5             5           5
180                                  Trucking       2             2           2
181                                   Uranium       1             1           1
182                     Utilities-Diversified       2             2           2
183              Utilities-Regulated Electric       1             1           1
184                 Utilities-Regulated Water       2             2           2
185                       Utilities-Renewable       9             9           9
186                          Waste Management       2             2           2
187                           Water Utilities      13            13          13
188       Wireless Telecommunication Services      20            20          20
189                                       NaN       6             6           6

     Symbol                                  Company Name Industry  Market Cap
1615    DDI                    DoubleDown Interactive Co.      NaN         620
1804    ECC                    Eagle Point Credit Company      NaN         536
1844    EIC                    Eagle Point Income Company      NaN           0
5275    SST                                       System1      NaN        1180
5416   TBLD  Thornburg Income Builder Opportunities Trust      NaN         555
6231   ZIMV                                        ZimVie      NaN         618

### Get all tickers in an industry sorted by market capitalization

In [10]:
industry = 'Auto Manufacturers'
print(sac[sac['Industry']==industry].sort_values(by=['Market Cap'], ascending=False).to_string())

     Symbol                         Company Name            Industry  Market Cap
4763   RIVN                    Rivian Automotive  Auto Manufacturers       41860
3277   LCID                          Lucid Group  Auto Manufacturers       37410
472    ARVL                              Arrival  Auto Manufacturers        2040
4570   PTRA                             Proterra  Auto Manufacturers        1600
2102   FFIE  Faraday Future Intelligent Electric  Auto Manufacturers        1540
2792   HYZN                         Hyzon Motors  Auto Manufacturers        1230
1127   CENN               Cenntro Electric Group  Auto Manufacturers         331
4990    SEV                           Sono Group  Auto Manufacturers         311
1859   ELMS         Electric Last Mile Solutions  Auto Manufacturers         222
5857    VEV                       Vicinity Motor  Auto Manufacturers         118
5897   VLCN                               Volcon  Auto Manufacturers          43
635    AYRO                           AYRO, Inc.  Auto Manufacturers          41
3788   MULN                    Mullen Automotive  Auto Manufacturers          27

### Large cap stocks > 10B

In [14]:
lg_cap = sac[sac['Market Cap']>10000]
lg_cap = lg_cap.set_index('Symbol')
lg_cap.to_csv('../data/sac_tickers_largecap.csv')
lg_cap.sort_values(by=['Market Cap'], ascending=False)

,Company Name,Industry,Market Cap
Symbol,,,
AAPL,Apple,"Technology Hardware, Storage & Periph...",2668120
MSFT,Microsoft,Software,2204400
GOOGL,Alphabet,Interactive Media & Services,1753600
GOOG,Alphabet,Interactive Media & Services,1751120
AMZN,Amazon.com,Internet & Direct Marketing Retail,1482170
...,...,...,...
CNXC,Concentrix,IT Services,10080
CHK,Chesapeake Energy,"Oil, Gas & Consumable Fuels",10080
TPL,Texas Pacific Land,"Oil, Gas & Consumable Fuels",10060
SNX,Synnex,"Electronic Equipment, Instruments & C...",10020
AZPN,Aspen Technology,Software,10010

In [15]:
mid_cap = sac[(sac['Market Cap']<10000) & (sac['Market Cap']>2000)]
mid_cap = mid_cap.set_index('Symbol')
mid_cap.to_csv('../data/sac_tickers_midcap.csv')
mid_cap.sort_values(by=['Market Cap'], ascending=False)

                      Company Name                        Industry  Market Cap
Symbol
ZION       Zions Bancorporation NA                           Banks        9970
LAD                  Lithia Motors                Specialty Retail        9960
BZ                         Kanzhun  Staffing & Employment Services        9930
OGN                  Organon & Co.                 Pharmaceuticals        9930
ACM                          AECOM      Construction & Engineering        9920
...                            ...                             ...         ...
NEX     NexTier Oilfield Solutions     Energy Equipment & Services        2020
XMTR                       Xometry  Specialty Industrial Machinery        2020
MANU             Manchester United                   Entertainment        2010
BLMN               Bloomin' Brands   Hotels, Restaurants & Leisure        2010
VSTO                 Vista Outdoor                Leisure Products        2010

[1218 rows x 3 columns]

# Identify ETFs from AlphaVantage's master list

In [16]:
av = pd.read_csv('../data/av_listed_tickers.csv')
av

,Symbol,Name,Exchange,AssetType,IpoDate,DelistingDate,Status
0,A,Agilent Technologies Inc,NYSE,Stock,1999-11-18,NaN,Active
1,AA,Alcoa Corp,NYSE,Stock,2016-10-18,NaN,Active
2,AAA,AAF FIRST PRIORITY CLO BOND ETF,NYSE ARCA,ETF,2020-09-09,NaN,Active
3,AAAU,Goldman Sachs Physical Gold ETF,BATS,ETF,2018-08-15,NaN,Active
4,AAC,Ares Acquisition Corporation - Class A,NYSE,Stock,2021-03-25,NaN,Active
...,...,...,...,...,...,...,...
12424,ZYME,Zymeworks Inc,NYSE,Stock,2017-04-28,NaN,Active
12425,ZYNE,Zynerba Pharmaceuticals Inc,NASDAQ,Stock,2015-08-05,NaN,Active
12426,ZYXI,Zynex Inc,NASDAQ,Stock,2012-07-23,NaN,Active
12427,ZZK,NaN,NYSE ARCA,Stock,2020-07-22,NaN,Active
12428,ZZZ,TEST TICKER FOR UTP,NYSE ARCA,Stock,2014-10-31,NaN,Active

In [17]:
asset_types = av.groupby('AssetType', as_index=False, dropna=False).count()
asset_types

  AssetType  Symbol  Name  Exchange  IpoDate  DelistingDate  Status
0       ETF    3322  3322      3322     3322              0    3322
1     Stock    9107  9044      9107     9107              0    9107

In [18]:
etfs = av[av['AssetType']=='ETF']

In [19]:
etfs.groupby('Exchange', as_index=False, dropna=False).count()

    Exchange  Symbol  Name  AssetType  IpoDate  DelistingDate  Status
0       BATS     556   556        556      556              0     556
1     NASDAQ     457   457        457      457              0     457
2       NYSE     420   420        420      420              0     420
3  NYSE ARCA    1846  1846       1846     1846              0    1846
4   NYSE MKT      43    43         43       43              0      43

### Identify ETFs listed on NYSE and NASDAQ

* Then Identify Vanguard ETFs NOT on NYSE or NASDAQ (only 10 - we ignore those)

In [20]:
etfs_nn = etfs[(etfs['Exchange']=='NYSE')|(etfs['Exchange']=='NASDAQ')]
etfs_nn = etfs_nn.set_index('Symbol')
etfs_nn.sort_values(by=['Exchange'], ascending=True)
#etfs_nn.to_csv('../data/av_listed_tickers_etfs.csv')

,Name,Exchange,AssetType,IpoDate,DelistingDate,Status
Symbol,,,,,,
AADR,AdvisorShares Dorsey Wright ADR ETF,NASDAQ,ETF,2010-07-21,NaN,Active
FTXR,First Trust Nasdaq Transportation ETF,NASDAQ,ETF,2016-09-22,NaN,Active
FTXO,First Trust Nasdaq Bank ETF,NASDAQ,ETF,2016-10-07,NaN,Active
FTXN,First Trust Nasdaq Oil & Gas ETF,NASDAQ,ETF,2016-09-23,NaN,Active
FTXL,First Trust Nasdaq Semiconductor ETF,NASDAQ,ETF,2016-09-21,NaN,Active
...,...,...,...,...,...,...
IVH,Delaware Ivy High Income Opportunities Fund,NYSE,ETF,2013-05-29,NaN,Active
JCE,Nuveen Core Equity Alpha Fund,NYSE,ETF,2007-03-28,NaN,Active
JDD,Nuveen Diversified Dividend and Income Fund,NYSE,ETF,2003-09-29,NaN,Active
IGI,Western Asset Investment Grade Defined Opportu...,NYSE,ETF,2009-07-01,NaN,Active
ZTR,Virtus Total Return Fund Inc,NYSE,ETF,1989-06-30,NaN,Active

### Vanguard ETFs

In [21]:
vanguard_etfs = etfs[etfs['Name'].str.contains('Vanguard')]
vanguard_etfs.groupby('Exchange', as_index=False, dropna=False).count()

    Exchange  Symbol  Name  AssetType  IpoDate  DelistingDate  Status
0       BATS      10    10         10       10              0      10
1     NASDAQ      24    24         24       24              0      24
2  NYSE ARCA      46    46         46       46              0      46

In [22]:
vanguard_etfs_not_nn = etfs[(etfs['Name'].str.contains('Vanguard'))&(etfs['Exchange']=='BATS')]
vanguard_etfs_not_nn

,Symbol,Name,Exchange,AssetType,IpoDate,DelistingDate,Status
3691,ESGV,Vanguard ESG U.S. Stock ETF,BATS,ETF,2018-09-20,NaN,Active
11566,VCEB,Vanguard ESG U.S. Corporate Bond ETF,BATS,ETF,2020-09-24,NaN,Active
11627,VFLQ,Vanguard U.S. Liquidity Factor ETF,BATS,ETF,2018-02-15,NaN,Active
11628,VFMF,Vanguard U.S. Multifactor ETF,BATS,ETF,2018-02-15,NaN,Active
11629,VFMO,Vanguard U.S. Momentum Factor ETF,BATS,ETF,2018-02-15,NaN,Active
11630,VFMV,Vanguard U.S. Minimum Volatility ETF,BATS,ETF,2018-02-15,NaN,Active
11631,VFQY,Vanguard U.S. Quality Factor ETF,BATS,ETF,2018-02-15,NaN,Active
11632,VFVA,Vanguard U.S. Value Factor ETF,BATS,ETF,2018-02-15,NaN,Active
11826,VSGX,Vanguard ESG International Stock ETF,BATS,ETF,2018-09-20,NaN,Active
11870,VUSB,Vanguard Ultra-Short Bond ETF,BATS,ETF,2021-04-07,NaN,Active

### Extract list of tickers by sector

* Find sector, given ticker
* List all sectors
* List tickers in a sector, sorted by cap
* Eliminate ones that don't exist

In [33]:
ticker = 'FREYR'
sac[sac['Symbol']==ticker]

Empty DataFrame
Columns: [Symbol, Company Name, Industry, Market Cap]
Index: []

In [17]:
industries = sac.groupby('Industry', as_index=False, dropna=False).count().sort_values(by='Symbol', ascending=False).reset_index(drop=True)
print(industries.to_string())

                                     Industry  Symbol  Company Name  Market Cap
0                          Blank Check / SPAC     696           696         696
1                               Biotechnology     686           686         686
2                                       Banks     316           316         316
3                 Oil, Gas & Consumable Fuels     207           207         207
4                                    Software     195           195         195
5            Health Care Equipment & Supplies     167           167         167
6    Equity Real Estate Investment Trusts ...     167           167         167
7                             Capital Markets     153           153         153
8                             Pharmaceuticals     147           147         147
9                             Metals & Mining     118           118         118
10                                  Machinery     113           113         113
11                                IT Services     106           106         106
12                           Specialty Retail     102           102         102
13                                  Insurance     101           101         101
14   Electronic Equipment, Instruments & C...     100           100         100
15              Hotels, Restaurants & Leisure      98            98          98
16   Semiconductors & Semiconductor Equipment      97            97          97
17                       Software-Application      91            91          91
18                                  Chemicals      84            84          84
19                 Thrifts & Mortgage Finance      81            81          81
20           Health Care Providers & Services      79            79          79
21                                      Media      71            71          71
22                              Food Products      67            67          67
23             Commercial Services & Supplies      64            64          64
24                        Aerospace & Defense      63            63          63
25                Energy Equipment & Services      60            60          60
26                   Communications Equipment      60            60          60
27         Internet & Direct Marketing Retail      59            59          59
28                         Household Durables      57            57          57
29                      Professional Services      54            54          54
30                              Entertainment      53            53          53
31                    Software-Infrastructure      52            52          52
32               Interactive Media & Services      50            50          50
33              Diversified Consumer Services      47            47          47
34                       Electrical Equipment      46            46          46
35       Real Estate Management & Development      45            45          45
36                           Consumer Finance      41            41          41
37           Textiles, Apparel & Luxury Goods      41            41          41
38                            Medical Devices      40            40          40
39           Trading Companies & Distributors      38            38          38
40                          Building Products      36            36          36
41             Life Sciences Tools & Services      36            36          36
42                            Auto Components      35            35          35
43                         Electric Utilities      34            34          34
44   Mortgage Real Estate Investment Trust...      34            34          34
45   Technology Hardware, Storage & Periph...      32            32          32
46                 Construction & Engineering      32            32          32
47                                Road & Rail      30            30          30
48                          Personal Products      28            28          28
49                   Food & Staples Retailing      27            27          27
50                            Shell Companies      27            27          27
51                           Leisure Products      26            26          26
52                                  Beverages      26            26          26
53                     Health Care Technology      26            26          26
54                                     Marine      25            25          25
55                Health Information Services      24            24          24
56     Diversified Telecommunication Services      24            24          24
57                           Asset Management      21            21          21
58     Drug Manufacturers-Specialty & Generic      20            20          20
59   Independent Power and Renewable Elect...      20            20          20
60        Wireless Telecommunication Services      20            20          20
61                                   Airlines      20            20          20
62                     Containers & Packaging      19            19          19
63                    Medical Care Facilities      19            19          19
64                             Banks-Regional      19            19          19
65                                Automobiles      19            19          19
66                            Multi-Utilities      18            18          18
67                            Internet Retail      18            18          18
68             Diversified Financial Services      18            18          18
69            Information Technology Services      17            17          17
70                             Packaged Foods      16            16          16
71             Internet Content & Information      16            16          16
72                     Diagnostics & Research      15            15          15
73                       Advertising Agencies      14            14          14
74                              Gas Utilities      14            14          14
75                     Construction Materials      14            14          14
76                            Water Utilities      13            13          13
77                    Air Freight & Logistics      13            13          13
78             Medical Instruments & Supplies      13            13          13
79                         Auto Manufacturers      13            13          13
80              Education & Training Services      12            12          12
81                    Paper & Forest Products      12            12          12
82                         Household Products      12            12          12
83                           Telecom Services      11            11          11
84                                   Gambling      11            11          11
85           Other Industrial Metals & Mining      10            10          10
86               Electrical Equipment & Parts      10            10          10
87                          Computer Hardware       9             9           9
88                                    Tobacco       9             9           9
89                        Utilities-Renewable       9             9           9
90                           Multiline Retail       9             9           9
91                            Credit Services       9             9           9
92                      Electronic Components       8             8           8
93                               Distributors       8             8           8
94             Electronic Gaming & Multimedia       8             8           8
95                                Restaurants       8             8           8
96                              Oil & Gas E&P       8             8           8
97                             Semiconductors       7             7           7
98                              REIT-Mortgage       7             7           7
99                       Real Estate Services       7             7           7
100                         Insurance Brokers       7             7           7
101                            Apparel Retail       7             7           7
102                  Industrial Conglomerates       7             7           7
103            Specialty Industrial Machinery       7             7           7
104                   Communication Equipment       6             6           6
105                         Personal Services       6             6           6
106        Scientific & Technical Instruments       6             6           6
107                                Auto Parts       6             6           6
108                                       NaN       6             6           6
109        Furnishings, Fixtures & Appliances       6             6           6
110               Specialty Business Services       5             5           5
111                       Specialty Chemicals       5             5           5
112       Farm & Heavy Construction Machinery       5             5           5
113                          REIT-Diversified       5             5           5
114             Transportation Infrastructure       5             5           5
115                                   Leisure       5             5           5
116                             Farm Products       5             5           5
117                  Pharmaceutical Retailers       5             5           5
118            Oil & Gas Equipment & Services       5             5           5
119            Staffing & Employment Services       5             5           5
120                                      Gold       5             5           5
121                   Beverages-Non-Alcoholic       5             5           5
122                            Grocery Stores       5             5           5
123                          Healthcare Plans       5             5           5
124         Beverages-Wineries & Distilleries       4             4           4
125            Security & Protection Services       4             4           4
126                  Auto & Truck Dealerships       4             4           4
127                     Recreational Vehicles       4             4           4
128                   Real Estate-Development       4             4           4
129                              Broadcasting       4             4           4
130                   Airports & Air Services       4             4           4
131             Household & Personal Products       4             4           4
132                                     Solar       4             4           4
133             Building Products & Equipment       4             4           4
134            Other Precious Metals & Mining       4             4           4
135                    Packaging & Containers       4             4           4
136                          Mortgage Finance       4             4           4
137                       Insurance-Specialty       3             3           3
138            Pollution & Treatment Controls       3             3           3
139                                Publishing       3             3           3
140                Engineering & Construction       3             3           3
141             Insurance-Property & Casualty       3             3           3
142                 Rental & Leasing Services       3             3           3
143                     Apparel Manufacturing       3             3           3
144                      Consumer Electronics       2             2           2
145                                     Steel       2             2           2
146                                   Lodging       2             2           2
147                       Consulting Services       2             2           2
148                              Luxury Goods       2             2           2
149                        Oil & Gas Drilling       2             2           2
150                                  Trucking       2             2           2
151                Drug Manufacturers-General       2             2           2
152                   Home Improvement Retail       2             2           2
153                   Industrial Distribution       2             2           2
154                          Waste Management       2             2           2
155                       Oil & Gas Midstream       2             2           2
156                     Insurance-Diversified       2             2           2
157                 Utilities-Regulated Water       2             2           2
158                       Agricultural Inputs       2             2           2
159                               REIT-Retail       2             2           2
160              Internet Software & Services       2             2           2
161                               REIT-Office       2             2           2
162                     Utilities-Diversified       2             2           2
163                           Marine Shipping       2             2           2
164              Utilities-Regulated Electric       1             1           1
165                       Tools & Accessories       1             1           1
166                                   Uranium       1             1           1
167                                Healthcare       1             1           1
168                         Banks-Diversified       1             1           1
169                         Beverages-Brewers       1             1           1
170                            Insurance-Life       1             1           1
171                     Insurance-Reinsurance       1             1           1
172            Integrated Freight & Logistics       1             1           1
173       Electronics & Computer Distribution       1             1           1
174  Investment Banking and Securities Dea...       1             1           1
175     Lessors of Other Real Estate Property       1             1           1
176                           Discount Stores       1             1           1
177  Data Processing, Hosting, and Related...       1             1           1
178                         Metal Fabrication       1             1           1
179                    Paper & Paper Products       1             1           1
180               Pharmaceutical Preparations       1             1           1
181                               Coking Coal       1             1           1
182  Photographic and Photocopying Equipme...       1             1           1
183                          REIT-Residential       1             1           1
184                            REIT-Specialty       1             1           1
185                   Real Estate-Diversified       1             1           1
186                  Residential Construction       1             1           1
187        Securities and Commodity Exchanges       1             1           1
188       Semiconductor Equipment & Materials       1             1           1
189  Pharmaceutical Preparation Manufactur...       1             1           1

In [30]:
sector = 'Software'
min_cap = 10000
sector_df = sac[(sac['Industry']==sector) & (sac['Market Cap']>=min_cap)].sort_values(by='Market Cap', ascending=False).reset_index(drop=True)
sector_df

   Symbol                       Company Name  Industry  Market Cap
0    MSFT                          Microsoft  Software     2204400
1    ADBE                              Adobe  Software      219190
2     CRM                     Salesforce.com  Software      205470
3    ORCL                             Oracle  Software      204260
4    INTU                             Intuit  Software      131490
5     SAP                             SAP SE  Software      127320
6     NOW                         ServiceNow  Software      114230
7    TEAM                          Atlassian  Software       67840
8    WDAY                            Workday  Software       61030
9    PANW                 Palo Alto Networks  Software       54910
10   FTNT                           Fortinet  Software       53950
11    VMW                             VMware  Software       49950
12   SNPS                           Synopsys  Software       47320
13   ADSK                           Autodesk  Software       45680
14   DDOG                            Datadog  Software       44630
15   CDNS             Cadence Design Systems  Software       42900
16   CRWD               CrowdStrike Holdings  Software       41060
17    NET                         Cloudflare  Software       37670
18    TTD                     The Trade Desk  Software       36680
19     ZS                            Zscaler  Software       33200
20     ZM          Zoom Video Communications  Software       32460
21      U                     Unity Software  Software       27960
22   ANSS                              ANSYS  Software       27160
23   PLTR              Palantir Technologies  Software       23660
24   HUBS                            HubSpot  Software       23340
25   BILL                  Bill.com Holdings  Software       22800
26   SPLK                             Splunk  Software       20490
27   DOCU                           DocuSign  Software       20060
28   PAYC                    Paycom Software  Software       20020
29   SSNC         SS&C Technologies Holdings  Software       19400
30   CHKP  Check Point Software Technologies  Software       19380
31   NUAN              Nuance Communications  Software       17880
32    TYL                 Tyler Technologies  Software       17510
33   NLOK                     NortonLifeLock  Software       16980
34    ZEN                            Zendesk  Software       14860
35   NICE                          NICE Ltd.  Software       14300
36   FICO                         Fair Isaac  Software       13070
37   CTXS                     Citrix Systems  Software       12740
38    PTC                           PTC Inc.  Software       12630
39     DT                          Dynatrace  Software       11840
40   OTEX                          Open Text  Software       11510
41    RNG                        RingCentral  Software       11360
42   PCTY                  Paylocity Holding  Software       10670
43   GLOB                            Globant  Software       10520
44   CDAY               Ceridian HCM Holding  Software       10140
45   AZPN                   Aspen Technology  Software       10010

In [32]:
path = '/Users/anupam/Desktop/Server/market_data/TIME_SERIES_DAILY/'

tickers = []
for t in sector_df['Symbol']:
    fpath = os.path.join(path, t+'.csv')
    if os.path.exists(fpath):
        tickers.append(t)
    else:
        print('File doesn\'t exist for {}'.format(fpath))
print("'{}'".format("','".join(tickers)))

'MSFT','ADBE','CRM','ORCL','INTU','SAP','NOW','TEAM','WDAY','PANW','FTNT','VMW','SNPS','ADSK','DDOG','CDNS','CRWD','NET','TTD','ZS','ZM','U','ANSS','PLTR','HUBS','BILL','SPLK','DOCU','PAYC','SSNC','CHKP','NUAN','TYL','NLOK','ZEN','NICE','FICO','CTXS','PTC','DT','OTEX','RNG','PCTY','GLOB','CDAY','AZPN'